from __future__ import annotations

import genanki

from generate_apkg import ROOT, note, write_deck


OUTPUT = ROOT / "anki-open-template-riscv-assembly.apkg"
DECK_ID = 2059400611


def build_notes(model: genanki.Model) -> list[genanki.Note]:
    return [
        note(
            model,
            [
                "RVF01",
                "fill",
                "RISC-V 常见实现采用 {{c1::little endian::端序}}，即低地址存放 {{c2::低字节::存储内容}}。",
                "",
                "little endian||低字节",
                "小端序的关键是“最低有效字节放在最低地址”。例如 $0x12345678$ 从低到高地址依次是 $0x78, 0x56, 0x34, 0x12$。",
                "",
                "",
            ],
            ["riscv", "assembly", "memory", "endianness", "fill"],
        ),
        note(
            model,
            [
                "RVC01",
                "choice",
                "在 little endian 下，把 $0x12345678$ 存到地址 $0x1000$ 时，地址 $0x1000$ 里的内容是什么？",
                "0x12||0x34||0x56||0x78",
                "4",
                "小端序把最低有效字节放在最低地址，所以最低地址处是 $0x78$。",
                "",
                "",
            ],
            ["riscv", "assembly", "memory", "endianness", "choice"],
        ),
        note(
            model,
            [
                "RVF02",
                "fill",
                "RV64 有 {{c1::32::数量}} 个通用寄存器，每个寄存器宽度是 {{c2::64 位::位宽}}。",
                "",
                "32||64 位",
                "RV64 的通用寄存器是 `x0 ~ x31`，也就是 32 个 64 位寄存器。",
                "",
                "",
            ],
            ["riscv", "assembly", "registers", "rv64", "fill"],
        ),
        note(
            model,
            [
                "RVF03",
                "fill",
                "寄存器 `x0` 的 ABI 名是 {{c1::zero::ABI 名}}，其值恒为 {{c2::0::固定值}}。",
                "",
                "zero||0",
                "`x0/zero` 是只读常量寄存器，写入会被忽略。",
                "",
                "",
            ],
            ["riscv", "assembly", "registers", "abi", "fill"],
        ),
        note(
            model,
            [
                "RVC02",
                "choice",
                "下列哪组寄存器属于典型的 callee-saved（被调用者保存）寄存器？",
                "`t0~t6`||`a0~a7`||`s0~s11`||`ra, a0, a1`",
                "3",
                "RISC-V 调用约定中，`s0~s11` 是 callee-saved；`t0~t6`、`a0~a7`、`ra` 通常视为 caller-saved。",
                "",
                "",
            ],
            ["riscv", "assembly", "abi", "calling-convention", "choice"],
        ),
        note(
            model,
            [
                "RVF04",
                "fill",
                "调用者保存（caller-saved）里常见的参数寄存器是 {{c1::a0~a7::参数组}}；被调用者保存（callee-saved）里常见的是 {{c2::s0~s11::保存组}}。",
                "",
                "a0~a7||s0~s11",
                "记忆时可以把 `a` 理解成 argument，`s` 理解成 saved。",
                "",
                "",
            ],
            ["riscv", "assembly", "abi", "calling-convention", "fill"],
        ),
        note(
            model,
            [
                "RVF05",
                "fill",
                "加载/存储后缀里：`b` 表示 {{c1::byte::1 字节}}，`h` 表示 {{c2::half word::2 字节}}，`w` 表示 {{c3::word::4 字节}}，`d` 表示 {{c4::double word::8 字节}}。",
                "",
                "byte||half word||word||double word",
                "在 RV64 里，`d` 对应 64 位，`w` 对应 32 位。",
                "",
                "",
            ],
            ["riscv", "assembly", "load-store", "sizes", "fill"],
        ),
        note(
            model,
            [
                "RVC03",
                "choice",
                "在 RV64 中，哪条指令会把 32 位数据零扩展到 64 位？",
                "`lw`||`lwu`||`ld`||`lh`",
                "2",
                "`lw` 会符号扩展，`lwu` 才是 zero-extend 到 64 位。",
                "",
                "",
            ],
            ["riscv", "assembly", "load-store", "signedness", "choice"],
        ),
        note(
            model,
            [
                "RVF06",
                "fill",
                "`lb` 是读 1 字节并 {{c1::符号扩展::扩展方式}}；`lbu` 是读 1 字节并 {{c2::零扩展::扩展方式}}。",
                "",
                "符号扩展||零扩展",
                "记忆法：带 `u` 的 load 常表示 unsigned / zero-extend。",
                "",
                "",
            ],
            ["riscv", "assembly", "load-store", "signedness", "fill"],
        ),
        note(
            model,
            [
                "RVF07",
                "fill",
                "RISC-V 里常说的 `i` 最常见表示 {{c1::immediate::立即数}} 版本，例如 `add` 对应 {{c2::addi::立即数版本}}。",
                "",
                "immediate||addi",
                "`andi`、`ori`、`xori`、`slti`、`slli` 等都属于立即数版本。",
                "",
                "",
            ],
            ["riscv", "assembly", "immediate", "fill"],
        ),
        note(
            model,
            [
                "RVQ01",
                "qa",
                "在 RISC-V 语境里，`RV64I` 中的 `I` 表示什么？",
                "",
                "它表示基础整数指令集（Integer）。",
                "例如 `RV64I` 是 64 位基础整数指令集；其他常见扩展还有 `M`、`A`、`F`、`D`、`C`。",
                "",
                "",
            ],
            ["riscv", "assembly", "isa", "rv64i", "qa"],
        ),
        note(
            model,
            [
                "RVC04",
                "choice",
                "下列哪条最准确地描述了 RISC-V 的内存访问模型？",
                "所有整数指令都可以直接访问内存||只有 load/store 指令能直接访问内存||只有跳转指令能访问内存||只有 `addi` 可以访问内存",
                "2",
                "RISC-V 是 load/store 架构，内存访问集中在 load/store 指令，其余运算主要在寄存器内完成。",
                "",
                "",
            ],
            ["riscv", "assembly", "memory", "architecture", "choice"],
        ),
        note(
            model,
            [
                "RVF08",
                "fill",
                "RISC-V 常见内存地址写法是 `offset(base)`，其有效地址由 {{c1::base::基址}} 与 {{c2::offset::偏移}} 相加得到。",
                "",
                "base||offset",
                "例如 `ld t0, 8(sp)` 访问的就是 `sp + 8`。",
                "",
                "",
            ],
            ["riscv", "assembly", "addressing", "load-store", "fill"],
        ),
        note(
            model,
            [
                "RVF09",
                "fill",
                "`R-type` 主要用于 {{c1::寄存器-寄存器::操作数形式}} 运算；`I-type` 常见于 {{c2::立即数::操作数形式}} 运算、{{c3::load::典型指令}} 与 {{c4::jalr::典型指令}}。",
                "",
                "寄存器-寄存器||立即数||load||jalr",
                "RISC-V 基本 32 位指令常见格式有 R/I/S/B/U/J 六种。",
                "",
                "",
            ],
            ["riscv", "assembly", "instruction-format", "fill"],
        ),
        note(
            model,
            [
                "RVC05",
                "choice",
                "下列哪种指令格式专门用于 store 指令？",
                "R-type||I-type||S-type||U-type",
                "3",
                "store 把立即数拆成高低两段放在 S-type 的不同字段里。",
                "",
                "",
            ],
            ["riscv", "assembly", "instruction-format", "store", "choice"],
        ),
        note(
            model,
            [
                "RVF10",
                "fill",
                "`B-type` 常用于 {{c1::条件分支::用途}}；`J-type` 常用于 {{c2::长跳转::用途}}。",
                "",
                "条件分支||长跳转",
                "例如 `beq` 属于 B-type，`jal` 属于 J-type。",
                "",
                "",
            ],
            ["riscv", "assembly", "instruction-format", "branch", "fill"],
        ),
        note(
            model,
            [
                "RVF11",
                "fill",
                "`lui rd, imm20` 会把立即数放到高 {{c1::20::高位数}} 位，本质上相当于左移 {{c2::12::左移位数}} 位。",
                "",
                "20||12",
                "例如 `lui t0, 0x12345` 会得到 `0x12345000`。这张卡先记住“高 20 位 / 左移 12 位”的核心语义。",
                "",
                "",
            ],
            ["riscv", "assembly", "instruction", "lui", "fill"],
        ),
        note(
            model,
            [
                "RVQ02",
                "qa",
                "`auipc` 指令通常用来做什么？",
                "",
                "它通常用于构造 PC 相对地址，即把当前 PC 与高位立即数相加。",
                "`auipc rd, imm20` 的效果是 `rd = pc + (imm20 << 12)`，常与 `jalr` 或 load/store 组合使用。",
                "",
                "",
            ],
            ["riscv", "assembly", "instruction", "auipc", "qa"],
        ),
        note(
            model,
            [
                "RVC06",
                "choice",
                "下列哪条最准确地描述了 `jal` 与 `jalr` 的区别？",
                "`jal` 是条件跳转，`jalr` 是无条件分支||`jal` 通常跳到标签，`jalr` 通常基于寄存器地址跳转||`jal` 不能保存返回地址，`jalr` 才能||两者都只能用于返回",
                "2",
                "`jal` 更常见于直接跳到标签，`jalr` 常见于通过寄存器间接跳转，比如函数返回。",
                "",
                "",
            ],
            ["riscv", "assembly", "control-flow", "jump", "choice"],
        ),
        note(
            model,
            [
                "RVF12",
                "fill",
                "伪指令 `ret` 通常展开成 {{c1::jalr x0, 0(ra)::真实指令}}；伪指令 `j label` 通常展开成 {{c2::jal x0, label::真实指令}}。",
                "",
                "jalr x0, 0(ra)||jal x0, label",
                "`ret` 本质上是“跳到返回地址且不保存新返回地址”；`j` 是不保存返回地址的无条件跳转。",
                "",
                "",
            ],
            ["riscv", "assembly", "pseudo-instruction", "control-flow", "fill"],
        ),
        note(
            model,
            [
                "RVC07",
                "choice",
                "伪指令 `mv t0, t1` 最常见会被汇编器展开成哪条真实指令？",
                "`add t0, t1, x0`||`addi t0, t1, 0`||`or t0, t1, zero`||`jalr t0, t1, 0`",
                "2",
                "`mv` 只是寄存器复制的伪指令，最常见展开是 `addi rd, rs, 0`。",
                "",
                "",
            ],
            ["riscv", "assembly", "pseudo-instruction", "registers", "choice"],
        ),
        note(
            model,
            [
                "RVF13",
                "fill",
                "伪指令 `not rd, rs` 常借助 {{c1::xori::真实指令}} 和立即数 {{c2::-1::关键立即数}} 实现；`neg rd, rs` 常借助 {{c3::sub::真实指令}} 与 {{c4::x0::零寄存器}} 实现。",
                "",
                "xori||-1||sub||x0",
                "`not` 是按位取反，`neg` 是做相反数。",
                "",
                "",
            ],
            ["riscv", "assembly", "pseudo-instruction", "alu", "fill"],
        ),
        note(
            model,
            [
                "RVC08",
                "choice",
                "伪指令 `bgt rs1, rs2, label` 最常见如何改写成真实分支关系？",
                "`blt rs1, rs2, label`||`bge rs1, rs2, label`||`blt rs2, rs1, label`||`bge rs2, rs1, label`",
                "3",
                "RISC-V 没有原生 `bgt`，通常用交换操作数后的 `blt rs2, rs1, label` 表达。",
                "",
                "",
            ],
            ["riscv", "assembly", "pseudo-instruction", "branch", "choice"],
        ),
        note(
            model,
            [
                "RVF14",
                "fill",
                "在 RV64 中，多数带 `w` 的算术/移位指令先按 {{c1::32 位::运算位宽}} 计算，再把结果 {{c2::符号扩展到 64 位::写回方式}}。",
                "",
                "32 位||符号扩展到 64 位",
                "例如 `addw`、`subw`、`sllw` 都保留 32 位语义；`lw` 也会把 32 位结果符号扩展到 64 位，但它是 load，不是 `*w` 算术/移位指令。",
                "",
                "",
            ],
            ["riscv", "assembly", "rv64", "w-instruction", "fill"],
        ),
        note(
            model,
            [
                "RVC09",
                "choice",
                "关于 RV64 中的 `w` 指令，下列哪项正确？",
                "它们和普通 64 位指令完全一样||它们只对低 16 位运算||它们只对低 32 位运算，然后符号扩展到 64 位||它们一定做零扩展",
                "3",
                "这是 RV64 容易混淆的点：`w` 家族保留 32 位语义，结果再做 sign-extension。",
                "",
                "",
            ],
            ["riscv", "assembly", "rv64", "w-instruction", "choice"],
        ),
        note(
            model,
            [
                "RVQ03",
                "qa",
                "为什么函数序言里常见 `addi sp, sp, -16`、保存 `ra` 和 `s0`，函数末尾再恢复它们？",
                "",
                "因为栈向低地址增长，函数需要先分配栈帧，再保存返回地址和被调用者保存寄存器，返回前恢复现场以保持调用约定。",
                "典型模式是先减小 `sp`，再 `sd ra, ...` / `sd s0, ...`，结束时 `ld` 恢复并把 `sp` 加回去。",
                "",
                "",
            ],
            ["riscv", "assembly", "stack", "calling-convention", "qa"],
        ),
        note(
            model,
            [
                "RVF15",
                "fill",
                "简单函数 `add:` 中，若参数在 `a0` 和 `a1`，返回值也放在 {{c1::a0::返回寄存器}}。",
                "",
                "a0",
                "RISC-V ABI 约定里，`a0` 和 `a1` 既可放参数，也可放返回值。",
                "",
                "",
            ],
            ["riscv", "assembly", "abi", "function-call", "fill"],
        ),
        note(
            model,
            [
                "RVC10",
                "choice",
                "下列哪条最适合作为“纯跳转，不保存返回地址”的真实指令？",
                "`jal ra, label`||`jal x0, label`||`jalr ra, x0, label`||`jalr ra, ra, 0`",
                "2",
                "把 `rd` 设成 `x0` 就表示不保留返回地址，所以 `j label` 常展开为 `jal x0, label`。",
                "",
                "",
            ],
            ["riscv", "assembly", "control-flow", "jump", "choice"],
        ),
        note(
            model,
            [
                "RVC11",
                "choice",
                "下列哪组最能体现“立即数版本通常带 `i`”的规律？",
                "`add` / `sub`||`add` / `addi`||`jal` / `jalr`||`ld` / `sd`",
                "2",
                "`addi`、`andi`、`ori`、`xori`、`slti` 等都体现了这个命名规律。",
                "",
                "",
            ],
            ["riscv", "assembly", "immediate", "naming", "choice"],
        ),
        note(
            model,
            [
                "RVQ04",
                "qa",
                "`lw` 和 `lwu` 在 RV64 中为什么容易写错？",
                "",
                "因为两者都只读取 32 位，但 `lw` 会符号扩展到 64 位，而 `lwu` 会零扩展到 64 位。",
                "如果读取的是带符号数，常用 `lw`；若希望把高 32 位清零，就应使用 `lwu`。",
                "",
                "",
            ],
            ["riscv", "assembly", "load-store", "rv64", "qa"],
        ),
        note(
            model,
            [
                "RVM01",
                "mindmap",
                "RISC-V 汇编总览。",
                "",
                "",
                "这张导图用于把速查笔记压缩成结构化总览，背面便于从大类回忆到细节。",
                '{"mindmap":[{"text":"RISC-V 汇编","children":[{"text":"基础：{{c1::little endian}}、32 个 64 位寄存器"},{"text":"数据大小：b/h/w/d"},{"text":"立即数：带 {{c2::i}} 的立即数版本"},{"text":"访存：load/store、offset(base)"},{"text":"控制流：branch、jal、jalr"},{"text":"格式：R / I / S / B / U / J"},{"text":"伪指令：mv / li / ret / j / not / neg"},{"text":"RV64 易错点：{{c3::w 指令先做 32 位运算再符号扩展到 64 位}}"}]}]}',
                "",
            ],
            ["riscv", "assembly", "overview", "mindmap"],
        ),
    ]


def main() -> None:
    write_deck(DECK_ID, "Anki Open Template :: RISC-V Assembly", OUTPUT, build_notes)


if __name__ == "__main__":
    main()
